config/routes.rb
Proto2::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out" 
  get "users/new"
  
  root :to => "sessions#new"
  
  namespace :admin do
    resources :members
    resources :products
    resources :logs, :only => [:index]
    resources :stores
  end 
  
  resources :sessions

  resources :members, :only => [:show, :index, :update] do
    resources :registers
    resources :offers
  end

  
end

app/models/member.rb
class Member
  include Mongoid::Document
  
  has_and_belongs_to_many :products
  
  belongs_to :store
  
  field :name, :type => String
  field :card, :type => String
  field :registered, :type => Boolean, :default => false
  field :reg_date, :type => Time
  field :email
  
  
  def registered=(value)
    write_attribute(:registered, value)
    if value == false
      self.reg_date = nil
    else
      self.reg_date = Time.now
    end
  end
  
  def offered?(offer)
      self.products.include?(offer)
  end
  
  def modify_products(product_list)
    if product_list
      product_list.each do |k, v|
        prod = Product.find(k)
        Rails.logger.info(">>>Member Model>>: #{k}, #{v} #{prod}")
        if v == "1"
          self.products.push prod unless self.products.include?(prod)
        else
          self.products.delete(prod) if self.products.include?(prod)  
        end
        self.save
      end
    end
  end

  def firstname
    return self.name.split(" ")[0]
  end
  
  
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  
  before_filter :check_authorisation
  respond_to :html, :json
  
  # GET /members
  # GET /members.json
  def index
    #Rails.logger.info(">>>ADMIN::Member Controller>>Index: #{@module_name}")
    @members = Member.all

    respond_with do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])
    @products = @member.products

    respond_with do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_with do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    Rails.logger.info(">>>Member Controller>>CREATE: #{params.inspect}, #{request.format}")
    if request.format == :json
      @member = Member.new(params[:member])
    else
      @member = Member.new(params[:memberandprod][:member])
    end

    respond_with do |format|
      if @member.save
        #UserMailer.welcome_email(@member).deliver
        
        reg_id = url_for member_registers_path(@member)
        #Rails.logger.info(">>>Member Controller>>CREATE: #{@member.inspect}")
        
        
        store = Store.find(params[:store])
        store.members.push @member
        @member.modify_products(params[:memberandprod][:products]) if params[:memberandprod]
                
        format.html { redirect_to admin_member_path(@member), notice: "For Registration use: #{reg_id}." }
        format.json { render :jsonify => @member, :status => :created, :location => member_path(@member) }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])
    #Rails.logger.info(">>>Member Controller>>UPDATE: #{params.inspect}")

    respond_with do |format|
      if @member.update_attributes(params[:memberandprod][:member])
        
        
        store = Store.find(params[:store])
        store.members.push @member
        
        @member.modify_products(params[:memberandprod][:products]) if params[:memberandprod][:products]
        
        format.html { redirect_to admin_member_path(@member), notice: 'Member was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_with do |format|
      format.html { redirect_to admin_members_url }
      format.json { head :ok }
    end
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  respond_to :html, :json
  
  def index
  end
  
  def show
    @member = Member.find(params[:id])
    respond_with do |format|
       format.html # show.html.erb
       format.json { render json: @member }
     end  
  end

end

app/views/admin/members/edit.html.erb
<% title "Edit member" %>

<div data-role="content">
	<%= form_for :memberandprod, :url => admin_member_path(@member), :method => :put do |form| %>
		<% if @member.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

				<ul>
					<% @member.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<%= form.fields_for @member do |f| %>

			<div class="field">
				<%= f.label :name %><br />
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<%= f.label :card %><br />
				<%= f.text_field :card %>
			</div>
			
			  <div class="field">
			    <%= f.label :email %><br />
			    <%= f.text_field :email %>
			  </div>

			<div data-role="fieldcontains">
			    <fieldset data-role="controlgroup">
			    	<legend>Store:</legend>
					<% if @member.store.nil? %>
						<%= select_tag( :store, options_for_select(Store.all.map{|s| [s.name, s.id]}))%>
					<% else %>
						<%= select_tag( :store, options_for_select(Store.all.map{|s| [s.name, s.id]}, :selected => @member.store.id ))%>
					<% end %>
				</fieldset>
			</div>

			
			<div data-role="fieldcontains">
			    <fieldset data-role="controlgroup">
			    	<legend>Registration:</legend>
					<%= f.radio_button :registered, "true" %>
					<%= f.label "registered_true" %>
					<%= f.radio_button :registered, "false" %>
					<%= f.label "registered_false" %>
				</fieldset>
			</div>
			
		<% end %>

		<div data-role="fieldcontains">
			<h3>Select/Update Product Offers</h3>
			<fieldset data-role="controlgroup">
				<%= form.fields_for :products do |f| %>
					<% Product.all.each do |prod| %>
						<p>
							<%= f.check_box prod.id, :checked => @member.offered?(prod), "type" => "checkbox" -%> 
							<%= f.label prod.id, prod.name -%>
						</p>
					<% end %>
	
				<% end %>
			</fieldset>
		</div>

		<div class="actions">
			<%= form.submit "update member" %>
		</div>
	<% end %>

</div>
<%= link_to 'Show', admin_member_path(@member), "data-role" => "button", "data-icon" => "gear" %>
<%= link_to 'Member List', admin_members_path, "data-role" => "button", "data-icon" => "back" %>

app/views/admin/members/index.html.erb
<% title "Members" %>

<div data-role = "content">
<ul data-role  = "listview">
<% @members.each do |member| %>

	<li data-role = "list-divider"><%= member.name %> </li>
	<li>
		<%= link_to admin_member_path(member)  do %>
			<h3>Member Information</h3>
			<p><%= member.card %></p>
			<p><%= member.email %></p>
			<% if member.registered? %>
				<p class="ui-li-aside">Registered: <%= member.reg_date %></p>
			<% end %>
			<div data-role="controlgroup" data-type="horizontal">
				<%= link_to 'Edit', edit_admin_member_path(member), "data-role" => "button", "data-icon" => "gear" %>
				<%= link_to 'Destroy', admin_member_path(member), :method => :delete, "data-role" => "button", "data-icon" => "delete" %>
			</div>
			
		<% end %>
	</li>


<% end %>
</ul>
</div>
<br />

<%= link_to 'New Member', new_admin_member_path, "data-role" => "button", "data-icon" => "plus" %>

app/views/admin/members/new.html.erb
<% title "New member" %>


<div data-role="content">
	<%= form_for :memberandprod, :url => admin_members_path do |form| %>
		<% if @member.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

				<ul>
					<% @member.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<%= form.fields_for @member do |f| %>

			<div class="field">
				<%= f.label :name %><br />
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<%= f.label :card %><br />
				<%= f.text_field :card %>
			</div>
			
			<div class="field">
				<%= f.label :email %><br />
				<%= f.text_field :email %>
			</div>
			
			
		<% end %>
		<div data-role="fieldcontains">
		    <fieldset data-role="controlgroup">
		    	<legend>Store:</legend>
				<%= select_tag( :store, options_for_select(Store.all.map{|s| [s.name, s.id]}) )%>
			</fieldset>
		</div>


		<div data-role="fieldcontains">
			<h3>Add Product Offers</h3>
			<fieldset data-role="controlgroup">
				<%= form.fields_for :products do |f| %>
					<% Product.all.each do |prod| %>
						<p>
							<%= f.check_box prod.id, "type" => "checkbox" -%> 
							<%= f.label prod.id, prod.name -%>
						</p>
					<% end %>
	
				<% end %>
			</fieldset>
		</div>

		<div class="actions">
			<%= form.submit "create member" %>
		</div>
	<% end %>

</div>

<%= link_to 'Member List', admin_members_path, "data-role" => "button", "data-icon" => "back" %>

app/views/admin/members/show.html.erb
<% title "Member Details" %>

<div data-role="content">
	<h3>Name: <%= @member.name %></h3>
	<p>
		<b>Card:</b>
		<%= @member.card %>
	</p>

	<p>
		<% if @member.registered? %>
			<b>Registered: <%= @member.reg_date %></b>
		<% else %>
			<b>Not Registered</b>
		<% end %>

	<p>
		<b>email:</b>
		<%= @member.email %>
	</p>
	</p>
	
	<h3>Offers Selected</h3>
	<ul data-role  = "listview">
		<%= render :partial => "shared/product", :collection => @products %>
	</ul>
</div>

<%= link_to 'Edit Member', edit_admin_member_path(@member), "data-role" => "button", "data-icon" => "gear" %>
<%= link_to 'Member List', admin_members_path, "data-role" => "button", "data-icon" => "back" %>