config/routes.rb
Proto2::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out" 
  get "users/new"
  
  root :to => "sessions#new"
  
  namespace :admin do
    resources :members
    resources :products
    resources :logs, :only => [:index]
    resources :stores
  end 
  
  resources :sessions

  resources :members, :only => [:show, :index, :update] do
    resources :registers
    resources :offers
  end

  
end

app/models/store.rb
class Store
  include Mongoid::Document
  
  has_many :members
    
  field :name
  
  
  
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
    
    before_filter :check_authorisation  
    respond_to :html, :json

    # GET /stores
    # GET /stores.json
    def index
      @stores = Store.all

      respond_with do |format|
        format.html # index.html.erb
      end
    end

    # GET /stores/1
    # GET /stores/1.json
    def show
      @store = Store.find(params[:id])

      respond_with do |format|
        format.html # show.html.erb
      end
    end

    # GET /stores/new
    # GET /stores/new.json
    def new
      @store = Store.new

      respond_with do |format|
        format.html # new.html.erb
      end
    end

    # GET /stores/1/edit
    def edit
      @store = Store.find(params[:id])
      #Rails.logger.info(">>>store Controller>>EDIT: #{@store.inspect}")
    end

    # POST /stores
    # POST /stores.json
    def create
      Rails.logger.info(">>>store Controller>>CREATE: #{params.inspect}")
      @store = Store.new(params[:store])

      respond_with do |format|
        if @store.save
          format.html { redirect_to admin_stores_path, notice: "store Created" }
        else
          format.html { render action: "new" }
        end
      end
    end

    # PUT /stores/1
    # PUT /stores/1.json
    def update
      @store = Store.find(params[:id])
      respond_with do |format|
        if @store.update_attributes(params[:store])
          format.html { redirect_to admin_stores_path, notice: 'store was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end

    # DELETE /stores/1
    # DELETE /stores/1.json
    def destroy
      @store = Store.find(params[:id])
      @store.destroy

      respond_with do |format|
        format.html { redirect_to admin_stores_path }
      end
    end


end

app/views/admin/stores/edit.html.erb
<% title "Edit Stores" %>

<div data-role="content">
	<%= form_for @store, :url => admin_store_path(@store) do |form| %>
	  <% if @store.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

	      <ul>
	      <% @store.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= form.label :name %><br />
	    <%= form.text_field :name %>
	  </div>

	  <div class="actions">
	    <%= form.submit "Save store" %>
	  </div>
	<% end %>
</div>
<%= link_to 'Show', admin_store_path(@store), "data-role" => "button", "data-icon" => "gear" %>
<%= link_to 'Store List', admin_stores_path, "data-role" => "button", "data-icon" => "back" %>

app/views/admin/stores/index.html.erb
<% title "Stores" %>

<div data-role = "content">
	<ul data-role  = "listview">
		<%= render :partial => "shared/store", :collection => @stores %>
	</ul>
</div>


<%= link_to 'New Store', new_admin_store_path, "data-role" => "button", "data-icon" => "plus" %>

app/views/admin/stores/new.html.erb
<% title "New Stores" %>

<div data-role="content">
	<%= form_for :store, :url => admin_stores_path do |f| %>
	  <% if @store.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

	      <ul>
	      <% @store.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>

	  <div class="actions">
	    <%= f.submit  "Save store"%>
	  </div>
	<% end %>
</div>

<%= link_to 'Store List', admin_stores_path, "data-role" => "button", "data-icon" => "back" %>

app/views/admin/stores/show.html.erb
<% title "Store Details" %>

<div data-role="content">
	<p>
		<b>Name:</b>
		<%= @store.name %>
	</p>


</div>

<%= link_to 'Edit Store', edit_admin_store_path(@store), "data-role" => "button", "data-icon" => "gear" %>
<%= link_to 'Delete Store', admin_store_path(@store), confirm: 'Are you sure?', method: :delete, "data-role" => "button", "data-icon" => "delete"  %>
<%= link_to 'Store List', admin_stores_path, "data-role" => "button", "data-icon" => "back" %>