config/routes.rb
Proto2::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out" 
  get "users/new"
  
  root :to => "sessions#new"
  
  namespace :admin do
    resources :members
    resources :products
    resources :logs, :only => [:index]
    resources :stores
  end 
  
  resources :sessions

  resources :members, :only => [:show, :index, :update] do
    resources :registers
    resources :offers
  end

  
end

app/models/product.rb
class Product
  include Mongoid::Document
  
  has_and_belongs_to_many :members
    
  mount_uploader :image, ImageUploader
    
  
  field :name
  field :desc
  field :image_file_name
  field :image
  field :long_desc
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    
    before_filter :check_authorisation  
    respond_to :html, :json

    # GET /products
    # GET /products.json
    def index
      @products = Product.all

      respond_with do |format|
        format.html # index.html.erb
        format.json { render json: @products }
      end
    end

    # GET /products/1
    # GET /products/1.json
    def show
      @product = Product.find(params[:id])

      respond_with do |format|
        format.html # show.html.erb
        format.json { render json: @product }
      end
    end

    # GET /products/new
    # GET /products/new.json
    def new
      @product = Product.new

      respond_with do |format|
        format.html # new.html.erb
        format.json { render json: @product }
      end
    end

    # GET /products/1/edit
    def edit
      @product = Product.find(params[:id])
      #Rails.logger.info(">>>product Controller>>EDIT: #{@product.inspect}")
    end

    # POST /products
    # POST /products.json
    def create
      #Rails.logger.info(">>>product Controller>>CREATE: #{params.inspect}")
      @product = Product.new(params[:product])

      respond_with do |format|
        if @product.save
          #Rails.logger.info(">>>product Controller>>CREATE: #{@product.inspect}")
          format.html { redirect_to admin_product_path(@product), notice: "Product Created" }
          #format.json { render :jsonify => @product, :status => :created, :location => product_path(@product) }
        else
          format.html { render action: "new" }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /products/1
    # PUT /products/1.json
    def update
      @product = Product.find(params[:id])
      respond_with do |format|
        if @product.update_attributes(params[:product])
          format.html { redirect_to admin_product_path(@product), notice: 'product was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1
    # DELETE /products/1.json
    def destroy
      @product = Product.find(params[:id])
      @product.destroy

      respond_with do |format|
        format.html { redirect_to admin_products_url }
        format.json { head :ok }
      end
    end


end

app/views/admin/products/_form.html.erb
<%= form_for admin_product(@product), :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<% title "Edit Offers" %>

<div data-role="content">
	<%= form_for @product, :url => admin_product_path(@product), :html => { "data-ajax" => "false", :multipart => true} do |form| %>
	  <% if @product.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

	      <ul>
	      <% @product.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= form.label :name %><br />
	    <%= form.text_field :name %>
	  </div>
	  <div class="field">
	    <%= form.label :desc %><br />
	    <%= form.text_field :desc %>
	  </div>

	  <div class="field">
	    <%= form.label :long_desc %><br />
	    <%= form.text_field :long_desc %>
	  </div>

	  <div class="field">
	    <%= form.label :image %><br />
	    <%= form.file_field :image %>
	  </div>	

	  <div class="actions">
	    <%= form.submit "Save Product" %>
	  </div>
	<% end %>
</div>
<%= link_to 'Show', admin_product_path(@product), "data-role" => "button", "data-icon" => "gear" %>
<%= link_to 'Offer List', admin_products_path, "data-role" => "button", "data-icon" => "back" %>

app/views/admin/products/index.html.erb
<% title "Offers" %>

<div data-role = "content">
	<ul data-role  = "listview">
		<%= render :partial => "shared/product", :collection => @products %>
	</ul>
</div>


<%= link_to 'New Product', new_admin_product_path, "data-role" => "button", "data-icon" => "plus" %>

app/views/admin/products/new.html.erb
<% title "New Products" %>

<div data-role="content">
	<%= form_for :product, :url => admin_products_path, :html => { :multipart => true, "data-ajax" => "false" } do |f| %>
	  <% if @product.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

	      <ul>
	      <% @product.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :desc %><br />
	    <%= f.text_field :desc %>
	  </div>

	  <div class="field">
	    <%= f.label :long_desc %><br />
	    <%= f.text_field :long_desc %>
	  </div>

	  <div class="field">
	    <%= f.label :image %><br />
	    <%= f.file_field :image %>
	  </div>


	  <div class="actions">
	    <%= f.submit  "Save Product"%>
	  </div>
	<% end %>
</div>

<%= link_to 'Product List', admin_products_path, "data-role" => "button", "data-icon" => "back" %>

app/views/admin/products/show.html.erb
<% title "Product Details" %>

<div data-role="content">
	<% if !@product.image_url.nil? %>
		<p>
			<%= image_tag @product.image_url %>
		</p>
	<% end %>

	<p>
		<b>Name:</b>
		<%= @product.name %>
	</p>

	<p>
		<b>Short Description:</b>
		<%= @product.desc %>
	</p>
	
	<div data-role="collapsible" data=collasped="true">
			<h3>Long Description:</h3>
			<p><%= @product.long_desc %></p>
	</div>
	
	


</div>

<%= link_to 'Edit Product', edit_admin_product_path(@product), "data-role" => "button", "data-icon" => "gear" %>
<%= link_to 'Delete Product', admin_product_path(@product), confirm: 'Are you sure?', method: :delete, "data-role" => "button", "data-icon" => "delete"  %>
<%= link_to 'Product List', admin_products_path, "data-role" => "button", "data-icon" => "back" %>